---
- name: Install Git on EC2 instance
  hosts: 34.239.101.165  # Replace with the actual IP or hostname of your EC2 instance
  become: yes

  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      tags:
        - update_cache

    - name: Install Git
      apt:
        name: git
        state: present
      tags:
        - install_git
